added planet category with its test class
gabrielbarker/qual-id pull request #29
Opened 2020-10-01 18:39 UTC by Augilar

I have created a new class for planets and added it into '__category map' and created a new test class for planets.

I am new to open source and happy to contribute 😁

2020-10-01 20:44 UTC, gabrielbarker requested changes
Hey @Augilar , thanks for taking the time to contribute! I've just spotted a couple of little tweaks, but other than that it looks great 🙂

2020-10-01 20:44 UTC, gabrielbarker commented on qual_id/categories/planet.py
> +        'jupiter',
what about saturn? 😂

2020-10-01 20:44 UTC, gabrielbarker commented on test/categories/test_planet.py
> +class TestColor(unittest.TestCase):
```suggestion
class TestPlanet(unittest.TestCase):
```

2020-10-01 20:46 UTC, Augilar commented on qual_id/categories/planet.py
> +        'jupiter',
How did I forget the best planet 😂

2020-10-01 20:48 UTC, Augilar commented on test/categories/test_planet.py
> +class TestColor(unittest.TestCase):
Sorry for that !!

2020-10-02 07:06 UTC, Augilar commented
@gabrielbarker since language category has been merged do i have to change my pattern file to get my PR merged ?

2020-10-02 08:04 UTC, gabrielbarker commented
Yeah @Augilar , since there's a conflict you'll have to resolve it by changing the file. You should be able to do it in the browser though I think, by clicking `Resolve conflicts`. Let me know if you need any help as it can be confusing 🙂

2020-10-02 08:14 UTC, Augilar commented
@gabrielbarker Why are checks failing ? I have changed the file by clicking `Resolve conflicts` and then clicked `resolve` and then `merge`. Have I done something wrong ?

2020-10-02 08:22 UTC, gabrielbarker commented
So if you look at the log for the test run [here](https://travis-ci.com/github/gabrielbarker/qual-id/jobs/394072341), you can see that the unit test for the pattern file has failed, and the error message is `"language": Language(),
SyntaxError: invalid syntax`. This tells us that the problem is to do with the __category_map because that's where that code is. If you then look at your changes [here](https://github.com/gabrielbarker/qual-id/pull/29/files) we can see that there is a missing comma after `Planet()` 🙂

The error messages aren't that great, I might look at improving them

2020-10-02 08:22 UTC, gabrielbarker requested changes

2020-10-02 08:22 UTC, gabrielbarker commented on qual_id/pattern.py
> +      "planet": Planet()
Here's the offending line
```suggestion
      "planet": Planet(),
```

2020-10-02 08:33 UTC, Augilar commented
Thanks for making me understand my mistake 😄.
I will improve and contribute more.

2020-10-02 08:34 UTC, gabrielbarker approved these changes

2020-10-02 08:34 UTC, merged

2020-10-02 08:35 UTC, gabrielbarker commented
Thanks a lot @Augilar ! No one likes conflicts, but you handled them like a pro 💪

2020-10-02 08:37 UTC, Augilar commented
Thanks a lot. I am happy that I am learnt how to handle conflicts from this contribution 😁

2020-10-02 08:38 UTC, Augilar commented
Thanks a lot as I have learnt how to handle conflicts from this contribution 😁