Added categories : "clothing" and "sports"
gabrielbarker/qual-id pull request #36
Opened 2020-10-02 16:51 UTC by soum-sr

2020-10-02 23:21 UTC, gabrielbarker requested changes
Thanks for the contribution @soum-sr 
Both of these new categories need test classes. See other categories for details 
🙂

2020-10-03 05:38 UTC, soum-sr commented
Hi, I've added the test_classes. Thank you 🙂

2020-10-03 15:26 UTC, gabrielbarker approved these changes

2020-10-03 15:27 UTC, gabrielbarker approved these changes

2020-10-03 15:29 UTC, gabrielbarker approved these changes

2020-10-03 15:33 UTC, gabrielbarker approved these changes

2020-10-03 15:34 UTC, gabrielbarker commented
Hey @soum-sr I just had to fix some merge conflicts and update the tests due to some changes I made last night. Should be good to go now, thanks for the contribution!

2020-10-03 15:34 UTC, merged