Adding data to existing categories
gabrielbarker/qual-id pull request #37
Opened 2020-10-02 20:01 UTC by NouranBakry

I added data into the categories [book, city, country, color, music, electronic, language]

2020-10-02 23:27 UTC, gabrielbarker requested changes
Hey @NouranBakry , great contribution, thanks!
Unfortunately I've found some duplicates. There may be more other than the ones I've found, but I've added comments. Please could you remove them?

2020-10-02 23:27 UTC, gabrielbarker commented on qual_id/categories/book.py
> +            'business',
duplicate

2020-10-02 23:27 UTC, gabrielbarker commented on qual_id/categories/instrument.py
> +        'cello'
duplicate

2020-10-02 23:27 UTC, gabrielbarker commented on qual_id/categories/language.py
> +            'Persian',
duplicate

2020-10-02 23:27 UTC, gabrielbarker commented on qual_id/categories/music.py
> +            'rock'
duplicate

2020-10-02 23:55 UTC, NouranBakry commented
Of course I will remove them now. Sorry for the inconvenience.

2020-10-03 01:56 UTC, gabrielbarker requested changes

2020-10-03 01:56 UTC, gabrielbarker commented on qual_id/categories/country.py
> +            'Austria',
duplicate

2020-10-03 01:57 UTC, gabrielbarker commented
It's ok @NouranBakry 🙂  but there is still a failing test in the countries category. I've put a comment on but there could be others

2020-10-03 02:08 UTC, gabrielbarker approved these changes
Nice!

2020-10-03 02:09 UTC, merged

2020-10-03 02:09 UTC, gabrielbarker commented
Thanks a lot for the contribution @NouranBakry ! You've went above and beyond  🙂  🎉

2020-10-03 02:10 UTC, NouranBakry commented
Thank you so much for giving me the chance to make my first contribution 😊