Added the Festivals category, in alphabetical order.
gabrielbarker/qual-id pull request #55
Opened 2020-10-06 13:09 UTC by PravunathSingh

Here I have tried to add at least one major festival for each letter.

2020-10-06 14:21 UTC, gabrielbarker requested changes
One problem is that values need to be lower case and single words. I've checked and you have about 10 here that are just one word which would be great! Could throw in 'easter' and 'hanukkah' too? Maybe just 'valentines' as well? Let me know your thoughts

You also need to add a test class and add this class to the map in 'pattern.py'. There are more details in contributing.md and in the issue description 🙂

2020-10-06 14:27 UTC, PravunathSingh commented
Thanks a lot @gabrielbarker  for the insights, I'll definitely work on the changes and let you know

2020-10-06 14:46 UTC, PravunathSingh commented
Hey @gabrielbarker I have made the changes, but two of my codecov checks are failing, could you provide some insights regarding them

2020-10-06 16:40 UTC, GoldDust69 commented
> Hey @gabrielbarker I have made the changes, but two of my codecov checks are failing, could you provide some insights regarding them

Hey there, it looks like you're still missing the test class for this which needs to be created in test/categories :)

2020-10-06 16:41 UTC, GoldDust69 commented
Hey there, it looks like you're still missing the test class for this which needs to be created in test/categories :)

2020-10-06 16:57 UTC, PravunathSingh commented
Hey, @GoldDust69 thanks for the help :).

2020-10-06 16:59 UTC, PravunathSingh commented
Hey, @gabrielbarker I've made all the changes, hopefully this time my changes would be approved. It would be great if you could review them

2020-10-06 23:17 UTC, gabrielbarker requested changes

2020-10-06 23:17 UTC, gabrielbarker commented on qual_id/categories/anime.py
> +from ..category import Category
Please can you remove this category file and add it (along with tests etc.) in a separate PR?

2020-10-07 03:12 UTC, PravunathSingh commented
Hey, @gabrielbarker I've deleted the anime.py file from this PR, as you said. I'm really for that mistake, I didn't notice it was there. :(

2020-10-07 08:15 UTC, gabrielbarker approved these changes
Looks great this time!

2020-10-07 08:16 UTC, merged

2020-10-07 08:16 UTC, gabrielbarker commented
Thanks so much for the contribution @PravunathSingh ! 🙂 🎉

2020-10-07 08:19 UTC, PravunathSingh commented
Thanks a lot @gabrielbarker for all the suggestions and guidance!!. Learnt a lot while contributing to this.

Looking forward to making more and better contributions to this repo :)

2020-10-07 08:20 UTC, gabrielbarker commented
I'm so pleased! Thanks @PravunathSingh !