added new category electronics, included in pattern class and written…
gabrielbarker/qual-id pull request #9
Opened 2020-09-30 17:46 UTC by mephi007

Added new category Electronics
Included in pattern class
Written test class

2020-09-30 21:16 UTC, gabrielbarker commented on qual_id/categories/electronic.py
> +        'Desktop',
```suggestion
        'desktop',
```
This should be lowercase

2020-09-30 21:19 UTC, gabrielbarker requested changes

2020-09-30 21:19 UTC, gabrielbarker commented on qual_id/categories/electronic.py
> +        'Desktop',
```suggestion
        'desktop',
```
This should be lowercase

2020-09-30 21:19 UTC, gabrielbarker commented on qual_id/categories/electronic.py
> +		'headPhones',
```suggestion
	'headphones',
```
No need for camelcase

2020-09-30 21:19 UTC, gabrielbarker commented on qual_id/categories/electronic.py
> +		'fan',
please fix the alignment of these elements

2020-09-30 21:19 UTC, gabrielbarker commented on test/categories/test_electronic.py
> +class TestElectronic(unittest.TestCase):
If you make sure that you have the latest changes from the original repo, the way to write unit tests has been simplified. See any other test class for reference

2020-09-30 21:20 UTC, gabrielbarker commented
Hey @mephi007 
I've put some comments on, just some small tweaks, thanks a lot for the new category!
🙂

2020-10-01 04:26 UTC, mephi007 commented
hey @gabrielbarker, I am not able understand, how build is failing?

2020-10-01 07:54 UTC, gabrielbarker approved these changes
Thanks for fixing those issues!

2020-10-01 07:54 UTC, gabrielbarker commented on qual_id/pattern.py
>        "instrument": Instrument()
```suggestion
      "instrument": Instrument(),
```
You missed a comma @mephi007 
Easy to do, especially in python 🙂

2020-10-01 07:55 UTC, gabrielbarker requested changes
Once the comma is added this should pass and be ready to go

2020-10-01 08:25 UTC, gabrielbarker approved these changes
Looks good!

2020-10-01 08:39 UTC, gabrielbarker approved these changes

2020-10-01 08:39 UTC, merged

2020-10-01 08:39 UTC, gabrielbarker commented
Thanks again @mephi007 , nice work 🙂

2020-10-01 08:44 UTC, mephi007 commented
Thank you so much @gabrielbarker